### ISSUE TITLE
No permite realizar el curso.

### ISSUE THREAD

**Issue by jluna80** [InfoFractal/if_moodle_sence#18]
Al tener un curso configurado no permite el usuario ver el contenido luego de realizar su logeo en sence. Si el usuario no es alumno (ejemplo rol de docente) tampoco deja que entre al curso. Lo solucione editando el block_if_sence_loging.php linea 147

Original:
`            $text .=        '$("a[href*=\'/course/view.php?id='.$course->id.'\']").removeAttr("href");';`

Solución:
`if(!sence_validate_session($runalumno,$course->codsence) and is_only_student_in_course($userid,$course->id)){ 
            $text .=        '$("a[href*=\'/course/view.php?id='.$course->id.'\']").removeAttr("href");';
			}`

___

Por otro lado al usuario estar logeado tiene un solo curso disponible si embargo le muestra tres opciones para cerrar su sesión en SENCE.

**Comment by InfoFractal** [comment]
El fix para el último error donde se muestran varios botones de cerrar sesión será subido prontamente.
