### ISSUE TITLE
No se puede acceder a los cursos

### ISSUE THREAD

**Issue by cnutenor** [InfoFractal/if_moodle_sence#19]
he realizado todos los pasos de la integracion pero los estudiantes no pueden acceder a los cursos.

**Comment by InfoFractal** [comment]
Y que error sale exactamente? Están usando algún tema en específico en moodle?

**Comment by cnutenor** [comment]
Hola Gracias por responder. Estamos utilizando el tema Klass (https://moodle.org/plugins/theme_klass) y no aparece ningún mensaje de error, simplemente intentar logearse en un curso en el bloque lateral de SENCE no permite hacer clic.

**Comment by InfoFractal** [comment]
> Hola Gracias por responder. Estamos utilizando el tema Klass (https://moodle.org/plugins/theme_klass) y no aparece ningún mensaje de error, simplemente intentar logearse en un curso en el bloque lateral de SENCE no permite hacer clic.

Le sugiero que nos contacte en nuestra página o whatsapp, ya que el plugin debe ser adaptado para ese tema.
