### ISSUE TITLE
En instalaciones personalizadas falla el llamado del formulario

### ISSUE THREAD

**Issue by fanqxdev** [InfoFractal/if_moodle_sence#6]
Línea 119 de block_if_sence_login.php
`      $text .=                'url: "/moodle/blocks/if_sence_login/model/sence_data_filter.php",';`

Cambiando por 
`      $text .=                'url: "/blocks/if_sence_login/model/sence_data_filter.php",';`

funciona

**Comment by InfoFractal** [comment]
El plugin fue hecho para instalaciones por defecto, aceptamos parches para autodetectar los paths.

**Comment by fanqxdev** [comment]
Gracias por responder,
