### ISSUE TITLE
Valores asignados a urlRetoma y urlError incorrectos

### ISSUE THREAD

**Issue by fanqxdev** [InfoFractal/if_moodle_sence#7]
Acá no entiendo bien como debe quedar el valor asignado 
```
$text .=    '<input type="hidden" value="'.$new_link.'blocks/if_sence_login/pages/exito.php" name="UrlRetoma">';
$text .=    '<input type="hidden" value="'.$new_link.'blocks/if_sence_login/pages/error.php" name="UrlError">';
```
En nuestras purebas nos queda lo siguiente luego de la selección del curso en la vista de curso
`<input type="hidden" value="https://test.com/course/view.php?id=2blocks/if_sence_login/pages/exito.php" name="UrlRetoma">
`

**Comment by fanqxdev** [comment]
Hola nuevamente parece que tendría que ser así, 
````
$text .=    '<input type="hidden" value="/blocks/if_sence_login/pages/exito.php" name="UrlRetoma">';
$text .=    '<input type="hidden" value="/blocks/if_sence_login/pages/error.php" name="UrlError">';
````

**Comment by InfoFractal** [comment]
Que extraño, $new_link deberia contener el string "https://test.com/". Este es el valor que se manda al POST a Sence para que a su vez haga la redirección.

**Comment by fanqxdev** [comment]
Gracias por responder, en la instalación que tenemos , cuando esta dentro del área personal la url es https://test.com/my por lo que en ese caso estaría sobrando /my.  De acuerdo a la página en donde uno esté esa url va a ir cambiando como lo hizo en el primer caso. 

Una solución es usar la variable global    $CFG->wwwroot  en $newlink
